# MCP Integration Only
# Focus on external MCP server integration with minimal configuration

externalServers:
  enabled: true
  autoConnect: true
  retry:
    maxAttempts: 3
    delayMs: 1000
  servers:
    # Filesystem MCP Server - provides file operations
    - name: "filesystem"
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
      description: "Filesystem operations MCP server"
    
    # Example servers (uncomment to use):
    
    # - name: "git"
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-git", "--repository", "."]
    #   description: "Git repository operations"
    
    # - name: "postgres"
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://localhost/mydb"]
    #   description: "PostgreSQL database MCP server"
    #   env:
    #     DATABASE_URL: "postgresql://localhost/mydb"
    
    # - name: "sqlite"
    #   command: "npx" 
    #   args: ["-y", "@modelcontextprotocol/server-sqlite", "/path/to/database.db"]
    #   description: "SQLite database MCP server"

logging:
  level: "info"