# Docker Test Configuration with Lum-chan Setup
autoLoad:
  profiles:
    - name: "lum"
      path: "/app/examples/local-resources/lum-behavior.md"
      autoApply: true

# File scanning settings for Docker test environment
fileSettings:
  configFiles:
    claude: "CLAUDE.md"
    behavior: "*-behavior.md"
    custom: "*-config.md"
  includePaths:
    - "/app/examples/local-resources/"
    - "/app/examples/mcp/"
    - "/app/configs/"
  excludePatterns:
    - "*.tmp"
    - "*.backup"
    - "*~"
    - ".git/**"
    - "node_modules/**"
    - "dist/**"
    - "coverage/**"
  allowedExtensions:
    - ".md"
    - ".markdown"
    - ".txt"

# Directory scanning configuration
directoryScanning:
  recursive: true
  maxDepth: 3
  includeHidden: false
  followSymlinks: false

# Profile management
profileManagement:
  allowDuplicateNames: false
  autoNamePattern: "%filename%"
  defaultProfile: "lum"

# Logging configuration for Docker testing
logging:
  level: "debug"
  verboseFileLoading: true
  verboseProfileSwitching: true

# External servers disabled for local testing
externalServers:
  enabled: false
  servers: []
  autoConnect: false
  retry:
    maxAttempts: 3
    delayMs: 1000