# Standard Configuration - Recommended Setup
# Perfect for: Most users, development teams, production use

# Multiple profiles with clear organization
profiles:
  - name: "default"
    path: "CLAUDE.md"
  - name: "assistant"
    path: "profiles/dev-assistant.md"
  - name: "reviewer"
    path: "profiles/code-reviewer.md"

# Essential external servers
externalServers:
  - name: "filesystem"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    description: "File system operations"
  
  - name: "git"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-git", "."]
    description: "Git repository management"

# Production-ready logging
logging:
  level: "info"
  structuredLogging: true

# Basic monitoring
monitoring:
  enabled: true
  port: 3099
  healthEndpoints: true