# Local Resources Configuration with Character Behaviors
autoLoad:
  profiles:
    - name: "lum"
      path: "lum-behavior.md"
      autoApply: true

# File scanning settings for local development
fileSettings:
  configFiles:
    claude: "CLAUDE.md"
    behavior: "*-behavior.md"
    custom: "*-config.md"
  includePaths:
    - "."
  excludePatterns:
    - "*.tmp"
    - "*.backup"
    - "*~"
  allowedExtensions:
    - ".md"
    - ".markdown"
    - ".txt"

# Directory scanning configuration
directoryScanning:
  recursive: true
  maxDepth: 3
  includeHidden: false
  followSymlinks: false

# Profile management
profileManagement:
  allowDuplicateNames: false
  autoNamePattern: "%filename%"
  defaultProfile: "lum"

# Logging configuration for local development
logging:
  level: "debug"
  verboseFileLoading: true
  verboseProfileSwitching: true

# External servers disabled for local resource testing
externalServers:
  enabled: false
  servers: []
  autoConnect: false
