# Minimal Configuration Example
# Shows the bare minimum required settings

# Basic auto-loading
autoLoad:
  profiles:
    - name: "basic"
      path: "./examples/lum-behavior.md"

# Essential file settings
fileSettings:
  configFiles:
    claude: "CLAUDE.md"
  includePaths:
    - "./examples/"
  allowedExtensions:
    - ".md"

# Basic logging
logging:
  level: "info"