# Test Configuration for Development
# This is a minimal configuration for testing purposes

# Auto-loading settings
autoLoad:
  # Test profiles
  profiles:
    - name: "test-lum"
      path: "./examples/lum-behavior.md"
      autoApply: false
    - name: "test-pirate"
      path: "./examples/pirate-behavior.md"
      autoApply: false

# File loading settings
fileSettings:
  # Configuration file patterns for testing
  configFiles:
    claude: "CLAUDE.md"
    behavior: "*-behavior.md"
    custom: "*-config.md"
  
  # Test directories
  includePaths:
    - "./examples/"
    - "./tests/"
  
  # Test exclusion patterns
  excludePatterns:
    - "*.tmp"
    - "*.test"
    - "node_modules/**"
  
  # Test file extensions
  allowedExtensions:
    - ".md"
    - ".txt"

# Directory scanning for tests
directoryScanning:
  recursive: false  # Shallow scanning for tests
  maxDepth: 1
  includeHidden: false
  followSymlinks: false

# Profile management for tests
profileManagement:
  allowDuplicateNames: true  # Allow duplicates in tests
  autoNamePattern: "test_%filename%"
  defaultProfile: "test-default"

# Minimal logging for tests
logging:
  level: "error"  # Reduce noise in tests
  verboseFileLoading: false
  verboseProfileSwitching: false