name: 'Dependabot Auto-Merge'

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Run linting
        run: npm run lint
        
      - name: Run build
        run: npm run build
        
      - name: Get PR details
        id: pr-details
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const title = pullRequest.title.toLowerCase();
            const isSecurityUpdate = title.includes('security') || pullRequest.labels.some(label => label.name === 'security');
            const isMinorOrPatch = title.includes('patch') || title.includes('minor') || title.includes('deps:');
            const isMajorUpdate = title.includes('major');
            
            return JSON.stringify({
              isSecurityUpdate,
              isMinorOrPatch,
              isMajorUpdate,
              title: pullRequest.title
            });
            
      - name: Parse PR details
        id: parse-details
        run: |
          echo "PR_DETAILS=${{ steps.pr-details.outputs.result }}" >> $GITHUB_ENV
          
      - name: Auto-approve and merge
        if: >
          (fromJSON(env.PR_DETAILS).isSecurityUpdate) ||
          (fromJSON(env.PR_DETAILS).isMinorOrPatch && !fromJSON(env.PR_DETAILS).isMajorUpdate)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prDetails = JSON.parse(process.env.PR_DETAILS);
            const pullNumber = context.issue.number;
            
            // Add approval
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              event: 'APPROVE',
              body: `Auto-approving ${prDetails.isSecurityUpdate ? 'security update' : 'dependency update'}: ${prDetails.title}`
            });
            
            // Enable auto-merge
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              commit_title: prDetails.title,
              commit_message: `${prDetails.title}\n\nAuto-merged by Dependabot workflow after passing all checks.`,
              merge_method: 'squash'
            });
            
      - name: Comment on major updates
        if: fromJSON(env.PR_DETAILS).isMajorUpdate
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prDetails = JSON.parse(process.env.PR_DETAILS);
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `This is a **major version update** that requires manual review.

**Update:** ${prDetails.title}

Please review the changelog and breaking changes before merging.

- [ ] Review changelog
- [ ] Test locally
- [ ] Update documentation if needed
- [ ] Verify no breaking changes affect the codebase`
            });
            
      - name: Add labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prDetails = JSON.parse(process.env.PR_DETAILS);
            const labels = ['dependabot'];
            
            if (prDetails.isSecurityUpdate) {
              labels.push('security', 'auto-merged');
            } else if (prDetails.isMinorOrPatch && !prDetails.isMajorUpdate) {
              labels.push('auto-merged');
            } else if (prDetails.isMajorUpdate) {
              labels.push('major-update', 'needs-review');
            }
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });