name: 'Nightly Backup'

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2:00 AM UTC
  workflow_dispatch:      # Allow manual triggering
    inputs:
      retention_days:
        description: 'Days to retain backups'
        required: false
        default: '30'
        type: string

permissions:
  contents: write  # Required to upload artifacts and create releases

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper git info
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create backups directory
        run: mkdir -p backups
        
      - name: Set backup environment variables
        run: |
          echo "BACKUP_DIR=./backups" >> $GITHUB_ENV
          echo "RETENTION_DAYS=${{ inputs.retention_days || '30' }}" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
          
      - name: Run backup script
        run: |
          chmod +x ./scripts/backup.sh
          ./scripts/backup.sh
          
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: omni-mcp-hub-backup-${{ env.TIMESTAMP }}
          path: backups/omni-mcp-hub_*.tar.gz
          retention-days: ${{ inputs.retention_days || 30 }}
          compression-level: 0  # Already compressed
          
      - name: Create backup summary
        run: |
          echo "## Backup Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Backup Contents" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          ls -lh backups/ >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Nightly Backup Failed';
            const body = `The nightly backup job failed on ${new Date().toISOString()}.
            
            **Workflow:** ${context.workflow}
            **Run:** ${context.runNumber}
            **Commit:** ${context.sha}
            
            Please check the workflow logs for details.`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'backup', 'automation']
            });